apiVersion: v1
kind: Pod
metadata:
  name: crypto-ticker
  labels:
    app: crypto-ticker
spec:
  containers:
    - name: crypto-ticker
      image: ghcr.io/driesvb-dtgc/kubernetes-workshop-pxl-2021/<???>
      volumeMounts:
        - mountPath: <???>
          name: wallet-volume
      lifecycle:
        postStart:
          exec:
            command: ["wget", "https://storage.googleapis.com/kubernetes-workshop-pxl-2021/wallet.dat", "-P", "/crypto"]
  volumes:
    - name: wallet-volume
      emptyDir: <???>
